version: '3.9'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: renekemalandua/squad-nginx-react
    container_name: squad-fronted
    ports:
      - "3000:80"
    networks:
      - squadnet

networks:
  squadnet:
    driver: bridge
